# Summary Table Generation

This notebook generates a comprehensive summary table combining all publisher, journal, question, answer, discrepancy, and score data into a single CSV file for downstream analysis and publication.

Output saved to `save_summmary_table.csv`

In [2]:
from daemon_analysis_tools import load_answers_from_yaml, save_summary_table_to_csv, create_answers_summary_with_metadata, load_summary_table_from_csv

## Load processed data

In [3]:
grouped_questions = load_answers_from_yaml('../../data/processed/all_answers')

No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
ACS/applied_materials_and_interfaces/data_recommended has inconsistencies: skipped
ACS/applied_materials_and_interfaces/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/physics_of_plasmas/data_recommended Mismatch in discrepancy flags: False, True
AIP/physics_of_plasmas/data_recommended has inconsistencies: skipped
AIP/physics_of_plasmas/data_required Mismatch in discrepancy flags: False, True
AIP/physics_of_plasmas/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/review_of_scientific_instruments/data_recommended Mismatch in discrepancy flags: False, True
AIP/review_of_scientific_instruments/data_recommended has inconsistencies: skipped
AIP/review_of_scientific_instruments/data_required Mismatch in discrepancy flags: False, True
AIP/review_of_scientific_instruments/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/low_temperature_physics/data_recommended Mismatch in discrepancy flags: False, True
AIP/low_temperature_physics/data_recommended has inconsistencies: skipped
AIP/low_temperature_physics/data_required Mismatch in discrepancy flags: False, True
AIP/low_temperature_physics/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/journal_of_applied_physics/data_recommended Mismatch in discrepancy flags: False, True
AIP/journal_of_applied_physics/data_recommended has inconsistencies: skipped
AIP/journal_of_applied_physics/data_required Mismatch in discrepancy flags: False, True
AIP/journal_of_applied_physics/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/applied_physics_reviews/data_recommended Mismatch in discrepancy flags: False, True
AIP/applied_physics_reviews/data_recommended has inconsistencies: skipped
AIP/applied_physics_reviews/data_required Mismatch in discrepancy flags: False, True
AIP/applied_physics_reviews/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/applied_physics_letters/data_recommended Mismatch in discrepancy flags: False, True
AIP/applied_physics_letters/data_recommended has inconsistencies: skipped
AIP/applied_physics_letters/data_required Mismatch in discrepancy flags: False, True
AIP/applied_physics_letters/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/aip_advances/data_recommended Mismatch in discrepancy flags: False, True
AIP/aip_advances/data_recommended has inconsistencies: skipped
AIP/aip_advances/data_required Mismatch in discrepancy flags: False, True
AIP/aip_advances/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/apl_photonics/data_recommended Mismatch in discrepancy flags: False, True
AIP/apl_photonics/data_recommended has inconsistencies: skipped
AIP/apl_photonics/data_required Mismatch in discrepancy flags: False, True
AIP/apl_photonics/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/the_journal_of_chemical_physics/data_recommended Mismatch in discrepancy flags: False, True
AIP/the_journal_of_chemical_physics/data_recommended has inconsistencies: skipped
AIP/the_journal_of_chemical_physics/data_required Mismatch in discrepancy flags: False, True
AIP/the_journal_of_chemical_physics/data_required has inconsistencies: skipped
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
No discrepancies detected.
AIP/apl_materials/data_recommended Mismatch in discrepancy flags: False, True
AIP/apl_materials/data_recommended has inconsistencies: skipped

## Enrich with metadata

Add question text, answer descriptions, scoring weights, and discrepancy information from the metadata YAML files.

In [4]:
### each level can be enriched with metadata, see examples of the yamls in the files below
publishers_metadata = '../../data/metadata/metadata_examples/publishers_metadata_example.yaml'
journals_metadata = '../../data/metadata/metadata_examples/journals_metadata_example.yaml'
questions_metadata = '../../data/metadata/metadata_examples/questions_metadata_example.yaml'
answers_metadata= '../../data/metadata/metadata_examples/answers_metadata_example.yaml'

# create_answers_summary_with_metadata(grouped_question=grouped_questions,publishers_metadata_yaml=publishers_metadata,journals_metadata_yaml= journals_metadata,questions_metadata_yaml = questions_metadata, answers_metadata_yaml = answers_metadata)

summary_table = create_answers_summary_with_metadata(grouped_question=grouped_questions,questions_metadata_yaml=questions_metadata,answers_metadata_yaml=answers_metadata )

Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer
Warning: This question has a single answer

## Preview and save

Inspect the summary table and save to CSV.

In [5]:
summary_table

,publisher,journal,question_id,question_text,has_discrepancy,discrepancy_reason,final_answer,num_encoders,question_type,score
0,ACS,acs_energy_letters,rdp_exist,1. Existence of research data policy,False,None,Research Data Policy (RDP) exists.,2,multiple_choice,1.00
1,ACS,acs_energy_letters,data_sharing,3. Data sharing requirements in RDP,False,None,Data sharing encouraged but optional.,2,multiple_choice,0.00
2,ACS,acs_energy_letters,data_fair,4. FAIR data sharing (see https://www.go-fair....,False,None,Public data sharing on a FAIR repository encou...,2,multiple_choice,0.33
3,ACS,acs_energy_letters,data_availability,2. Data availability statement,False,None,Mentioned in the RDP but optional.,2,multiple_choice,0.50
4,ACS,acs_energy_letters,data_citability,5. Citability and findability of data,False,None,DOIs or other persistent identifiers recommend...,2,multiple_choice,0.50
...,...,...,...,...,...,...,...,...,...,...
3165,open journals,journal_of_open_source_software_(joss),code_quality,16. Code Quality Standards,True,Text not found,The journal policies specify criteria for refe...,2,multiple_choice,NaN
3166,open journals,journal_of_open_source_software_(joss),code_autotest,17. Automatic Testing,True,Text not found,The journal policies encourage/recommend autom...,2,multiple_choice,0.50
3167,open journals,journal_of_open_source_software_(joss),code_docs,18. Code Documentation,False,None,The journal policies require documentation of ...,2,multiple_choice,1.00
3168,open journals,journal_of_open_source_software_(joss),code_linting,19. Linting Standards,True,Text not found,The journal policies encourage/recommend linti...,2,multiple_choice,0.50
3169,open journals,journal_of_open_source_software_(joss),code_development,20. Code Development,False,None,The journal policies encourage/recommend stand...,2,multiple_choice,0.50

In [6]:
save_summary_table_to_csv(summary_table, path = './save_summmary_table.csv')

[info] CSV written → save_summmary_table.csv

In [7]:
load_summary_table_from_csv(path = './save_summmary_table.csv')

[info] CSV loaded ← save_summmary_table.csv

,publisher,journal,question_id,question_text,has_discrepancy,discrepancy_reason,final_answer,num_encoders,question_type,score
0,ACS,acs_energy_letters,rdp_exist,1. Existence of research data policy,False,NaN,Research Data Policy (RDP) exists.,2,multiple_choice,1.00
1,ACS,acs_energy_letters,data_sharing,3. Data sharing requirements in RDP,False,NaN,Data sharing encouraged but optional.,2,multiple_choice,0.00
2,ACS,acs_energy_letters,data_fair,4. FAIR data sharing (see https://www.go-fair....,False,NaN,Public data sharing on a FAIR repository encou...,2,multiple_choice,0.33
3,ACS,acs_energy_letters,data_availability,2. Data availability statement,False,NaN,Mentioned in the RDP but optional.,2,multiple_choice,0.50
4,ACS,acs_energy_letters,data_citability,5. Citability and findability of data,False,NaN,DOIs or other persistent identifiers recommend...,2,multiple_choice,0.50
...,...,...,...,...,...,...,...,...,...,...
3165,open journals,journal_of_open_source_software_(joss),code_quality,16. Code Quality Standards,True,Text not found,The journal policies specify criteria for refe...,2,multiple_choice,NaN
3166,open journals,journal_of_open_source_software_(joss),code_autotest,17. Automatic Testing,True,Text not found,The journal policies encourage/recommend autom...,2,multiple_choice,0.50
3167,open journals,journal_of_open_source_software_(joss),code_docs,18. Code Documentation,False,NaN,The journal policies require documentation of ...,2,multiple_choice,1.00
3168,open journals,journal_of_open_source_software_(joss),code_linting,19. Linting Standards,True,Text not found,The journal policies encourage/recommend linti...,2,multiple_choice,0.50
3169,open journals,journal_of_open_source_software_(joss),code_development,20. Code Development,False,NaN,The journal policies encourage/recommend stand...,2,multiple_choice,0.50